{
	"version": 1614993427,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/chao-sheet0.png",
		"images/cenario-sheet0.png",
		"images/facil-sheet0.png",
		"images/medio-sheet0.png",
		"images/dificill-sheet0.png",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/opçao-sheet0.png",
		"images/opçao-sheet1.png",
		"images/opçao-sheet2.png",
		"images/fundodemensagem-sheet0.png",
		"images/caixa1-sheet0.png",
		"images/caixa1-sheet1.png",
		"images/bolaa-sheet0.png",
		"images/particles.png",
		"images/fundodateladeniveis-sheet0.png",
		"images/cafixa-sheet0.png",
		"images/cenario2-sheet0.png",
		"images/fruta-sheet0.png",
		"images/igual-sheet0.png",
		"images/respostas-sheet0.png",
		"images/respostas-sheet1.png",
		"images/respostas-sheet2.png",
		"images/menos-sheet0.png",
		"images/colisor-sheet0.png",
		"images/fases1-sheet0.png",
		"images/fase2-sheet0.png",
		"images/fase3-sheet0.png",
		"images/fase4-sheet0.png",
		"images/seta-sheet0.png",
		"images/cenario3-sheet0.png",
		"images/splash-sheet0.png",
		"images/telademenu-sheet0.png",
		"images/play-sheet0.png",
		"images/creditos-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/fundopreto-sheet0.png",
		"images/logo-sheet0.png",
		"images/carregamento-sheet0.png",
		"images/barrabranca.png",
		"images/spritefont.png",
		"images/barrabran-sheet0.png",
		"images/proximo-sheet0.png",
		"images/pedras-sheet0.png",
		"images/pedras-sheet1.png",
		"images/pedras-sheet2.png",
		"images/arvore-sheet0.png",
		"images/quadro-sheet0.png",
		"media/00.ogg",
		"media/01.ogg",
		"media/02.ogg",
		"media/03.ogg",
		"media/04.ogg",
		"media/05.ogg",
		"media/06.ogg",
		"media/07.ogg",
		"media/08.ogg",
		"media/09.ogg",
		"media/010.ogg",
		"media/explicação da subtração.ogg",
		"media/qcficaram.ogg",
		"media/quantascaixas.ogg",
		"media/retirada das caixas.ogg",
		"media/frutas.ogg",
		"media/4frutas.ogg",
		"media/5 frusta.ogg",
		"media/6frutas.ogg",
		"media/mensagem de erro.ogg",
		"media/quantas frutas ainda sobrou.ogg",
		"media/vc tinha 12.ogg",
		"media/vc tinha 10.ogg",
		"media/vc tinha 8.ogg",
		"media/parabéns.ogg",
		"media/clik.ogg",
		"media/clik1.ogg",
		"media/clik2.ogg",
		"media/clik3.ogg",
		"media/pedraretiras.ogg",
		"media/primeira coluna.ogg",
		"media/segunda coluna.ogg"
	]
}